version: "3.9"

services:
  molaeng_back:
    build:
      context: ./molaeng_back
    container_name: molaeng_back
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${mysql_url}
      SPRING_DATASOURCE_USERNAME: ${mysql_username}
      SPRING_DATASOURCE_PASSWORD: ${mysql_password}
      TZ: "Asia/Seoul"

  molaeng_front:
    build:
      context: ./molaeng_front
    container_name: molaeng_front
    ports:
      - "8081:80"
    environment:
      TZ: "Asia/Seoul"

  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/home/ubuntu/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_dbname}
      MYSQL_USER: ${mysql_username}
      MYSQL_PASSWORD: ${mysql_password}
      TZ: "Asia/Seoul"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/home/ubuntu/redis:/data"
    environment:
      TZ: "Asia/Seoul"
